// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrxooE3nGs6OqNmdD9ohyf-xhT86phfZ4',
    appId: '1:683496989623:web:9f049e361b1e2059063e32',
    messagingSenderId: '683496989623',
    projectId: 'recipe-967d4',
    authDomain: 'recipe-967d4.firebaseapp.com',
    databaseURL: 'https://recipe-967d4-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-967d4.firebasestorage.app',
    measurementId: 'G-XKKG4M3NTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1K2KqaH_z_uSdPuYA2NTRG8du2ir8Dxg',
    appId: '1:683496989623:android:84367d0694f04015063e32',
    messagingSenderId: '683496989623',
    projectId: 'recipe-967d4',
    databaseURL: 'https://recipe-967d4-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-967d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0d5XjeQ5KvIhgiV-SiJ3Vhvs5zBykobo',
    appId: '1:683496989623:ios:c91fbacb0b95e1e7063e32',
    messagingSenderId: '683496989623',
    projectId: 'recipe-967d4',
    databaseURL: 'https://recipe-967d4-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-967d4.firebasestorage.app',
    androidClientId: '683496989623-9589rintipk6kddmsqmge7ud25pesbhr.apps.googleusercontent.com',
    iosClientId: '683496989623-1c7nie86pg5dq6up8caiku69jklrq2lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeDaily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0d5XjeQ5KvIhgiV-SiJ3Vhvs5zBykobo',
    appId: '1:683496989623:ios:c91fbacb0b95e1e7063e32',
    messagingSenderId: '683496989623',
    projectId: 'recipe-967d4',
    databaseURL: 'https://recipe-967d4-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-967d4.firebasestorage.app',
    androidClientId: '683496989623-9589rintipk6kddmsqmge7ud25pesbhr.apps.googleusercontent.com',
    iosClientId: '683496989623-1c7nie86pg5dq6up8caiku69jklrq2lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeDaily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrxooE3nGs6OqNmdD9ohyf-xhT86phfZ4',
    appId: '1:683496989623:web:7e09ca9eb66180d2063e32',
    messagingSenderId: '683496989623',
    projectId: 'recipe-967d4',
    authDomain: 'recipe-967d4.firebaseapp.com',
    databaseURL: 'https://recipe-967d4-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-967d4.firebasestorage.app',
    measurementId: 'G-WQYQETYEBQ',
  );
}
